import { CategoryData, ChartDataPoint, HotspotItem, KpiData } from './types';

export const MOCK_KPI: KpiData = {
  totalHotspots: 1248,
  newToday: 156,
  avgSentiment: 68.5,
  activeSources: 12,
};

export const MOCK_HOTSPOTS: HotspotItem[] = [
  {
    id: '1',
    rank: 1,
    title: '全球首款固态电池量产车发布',
    summary: '某新能源汽车品牌正式发布全球首款搭载固态电池的量产车型，续航里程突破1000公里，引发科技与汽车行业广泛关注。',
    relevance: 98,
    heatScore: 9850000,
    trend: 'new',
    category: '科技',
    source: '微博热搜',
    timestamp: '10 分钟前',
  },
  {
    id: '2',
    rank: 2,
    title: '新能源汽车补贴新政出台',
    summary: '相关部门联合发布最新新能源汽车补贴政策，重点倾斜于电池技术创新与充电基础设施建设，预计将重塑行业格局。',
    relevance: 95,
    heatScore: 8540000,
    trend: 'up',
    category: '财经',
    source: '今日头条',
    timestamp: '30 分钟前',
  },
  {
    id: '3',
    rank: 3,
    title: '某知名导演新片票房破十亿',
    summary: '春节档热门电影在上映首周票房突破十亿大关，口碑与票房双丰收，成为近期影视文化领域讨论度最高的话题。',
    relevance: 85,
    heatScore: 7620000,
    trend: 'down',
    category: '娱乐',
    source: '抖音热榜',
    timestamp: '1 小时前',
  },
  {
    id: '4',
    rank: 4,
    title: 'AI 大模型在医疗领域的最新突破',
    summary: '顶尖科研团队宣布其AI大模型在早期疾病筛查方面取得重大进展，准确率超越传统方案，开启智慧医疗新篇章。',
    relevance: 92,
    heatScore: 6890000,
    trend: 'up',
    category: '科技',
    source: '知乎热榜',
    timestamp: '2 小时前',
  },
  {
    id: '5',
    rank: 5,
    title: '周末出游人数创历史新高',
    summary: '随着天气转暖，各地迎来周末出游高峰，多个知名景区门票售罄，旅游消费市场展现出强劲的复苏势头与活力。',
    relevance: 78,
    heatScore: 5430000,
    trend: 'stable',
    category: '民生',
    source: '微博热搜',
    timestamp: '3 小时前',
  },
  {
    id: '6',
    rank: 6,
    title: '国际原油价格出现大幅波动',
    summary: '受多重地缘政治因素影响，国际原油市场本周经历剧烈震荡，分析师预测此轮波动可能对全球供应链产生连锁反应。',
    relevance: 88,
    heatScore: 4980000,
    trend: 'up',
    category: '国际',
    source: '新浪财经',
    timestamp: '4 小时前',
  },
  {
    id: '7',
    rank: 7,
    title: '某地发现大规模古代遗址',
    summary: '考古工作者在某省发掘出一处保存完好的大规模古代城池遗址，出土大量珍贵文物，为研究古代文明提供了新证据。',
    relevance: 75,
    heatScore: 3210000,
    trend: 'new',
    category: '文化',
    source: '百度热搜',
    timestamp: '5 小时前',
  },
  {
    id: '8',
    rank: 8,
    title: '国内首款 3A 游戏销量破千万',
    summary: '国产单机大作全球销量正式突破一千万份，创下中国游戏产业新里程碑，受到全球玩家和媒体的一致好评。',
    relevance: 90,
    heatScore: 2980000,
    trend: 'up',
    category: '游戏',
    source: 'B站热搜',
    timestamp: '6 小时前',
  },
  {
    id: '9',
    rank: 9,
    title: '今年首场强冷空气即将来袭',
    summary: '气象台发布寒潮蓝色预警，预计未来三天我国大部地区将经历断崖式降温，部分地区降温幅度可达 10 度以上。',
    relevance: 82,
    heatScore: 2750000,
    trend: 'up',
    category: '民生',
    source: '今日头条',
    timestamp: '6.5 小时前',
  },
  {
    id: '10',
    rank: 10,
    title: '知名网红带货产品被曝涉嫌虚假宣传',
    summary: '某千万粉丝网红在直播间售卖的美容仪被多名消费者投诉存在虚假宣传，相关市场监管部门已介入调查。',
    relevance: 79,
    heatScore: 2450000,
    trend: 'down',
    category: '社会',
    source: '微博热搜',
    timestamp: '7 小时前',
  },
  {
    id: '11',
    rank: 11,
    title: '商业航天公司成功发射可重复使用火箭',
    summary: '国内某民营航天企业自主研发的可重复使用火箭圆满完成首次垂直起降试验，标志着商业航天技术迈上新台阶。',
    relevance: 96,
    heatScore: 2100000,
    trend: 'new',
    category: '科技',
    source: '知乎热榜',
    timestamp: '8 小时前',
  },
  {
    id: '12',
    rank: 12,
    title: '新一线城市发布落户新政',
    summary: '多个新一线城市相继出台进一步放宽落户限制的政策，旨在吸引更多高校毕业生和高技能人才流入。',
    relevance: 85,
    heatScore: 1890000,
    trend: 'stable',
    category: '房产',
    source: '百度热搜',
    timestamp: '10 小时前',
  },
];

export const MOCK_TREND_DATA: ChartDataPoint[] = [
  { time: '08:00', '固态电池': 200, '新能源补贴': 800, 'AI大模型': 400 },
  { time: '09:00', '固态电池': 1200, '新能源补贴': 950, 'AI大模型': 450 },
  { time: '10:00', '固态电池': 3500, '新能源补贴': 1100, 'AI大模型': 500 },
  { time: '11:00', '固态电池': 6800, '新能源补贴': 1050, 'AI大模型': 600 },
  { time: '12:00', '固态电池': 8500, '新能源补贴': 900, 'AI大模型': 800 },
  { time: '13:00', '固态电池': 9850, '新能源补贴': 854, 'AI大模型': 689 },
];

export const MOCK_CATEGORY_DATA: CategoryData[] = [
  { name: '科技', value: 35, color: '#4f46e5' }, // indigo-600
  { name: '娱乐', value: 25, color: '#f43f5e' }, // rose-500
  { name: '财经', value: 20, color: '#10b981' }, // emerald-500
  { name: '民生', value: 10, color: '#facc15' }, // yellow-400
  { name: '其他', value: 10, color: '#cbd5e1' }, // slate-300
];
